/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.Sinopsis;
import Classes.Judul;
import Classes.Harga;
import Classes.HargaVip;
import Classes.ArrayKursi;
import javax.swing.JOptionPane;
//import Classes.Jumlah;

/**
 *
 * @author Yunia
 */
public class SinopsisFilm extends javax.swing.JFrame {

    /**
     * Creates new form SinopsisFilm
     */
    //String yang nantinya untuk mengambil nilai judul, harga, hargavip, dan sinopsis
    //Butuh Clas yang menampung judul, harga, hargavip, dan sinopsis
    private String judul;
    private int jumlah;
    private String harga;
    private String hargavip;
    private String sinopsis;
    private ArrayKursi chair = new ArrayKursi();

    //objek untuk mengambil isi array di Kelas sinopsis Package Classes
    Sinopsis sin = new Sinopsis();
    Judul jud = new Judul();
    //Jumlah jum = new Jumlah();
    Harga har = new Harga();
    HargaVip harV = new HargaVip();

    public SinopsisFilm() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setMinimumSize(new java.awt.Dimension(600, 425));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pict/brightburn.jpg"))); // NOI18N
        jLabel1.setText("BrightBurn");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(205, 39, 110, 123);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pict/jus1.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 200, 110, 130);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pict/aveng1.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(65, 39, 110, 123);

        jButton1.setText("Info");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(65, 168, 60, 23);

        jButton2.setText("Info");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(205, 168, 60, 23);

        jButton3.setText("Info");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(65, 338, 60, 23);

        jButton4.setText("Info");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(205, 338, 60, 23);

        jLabel5.setText("Judul");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 90, 60, 14);

        jTextField1.setEditable(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(420, 90, 140, 20);

        jTextField2.setEditable(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(445, 169, 120, 20);

        jLabel6.setText("Harga");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(333, 172, 50, 14);

        jTextField3.setEditable(false);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(445, 197, 120, 20);

        jLabel7.setText("ECO");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(393, 172, 34, 14);

        jLabel8.setText("VIP2");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(393, 200, 34, 14);

        jLabel9.setText("Sinopsis");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(330, 250, 50, 14);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(399, 250, 166, 96);

        jButton5.setText("Pesan");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(480, 350, 80, 23);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pict/alad1.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 200, 110, 130);

        jLabel2.setText("Jumlah");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 120, 50, 14);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(420, 120, 140, 20);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pict/ini 2.jpeg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 580, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (jTextField4.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data belum lengkap");
        } else {
            judul = jTextField1.getText();
            jumlah = Integer.parseInt(jTextField4.getText());
            harga = jTextField2.getText();
            hargavip = jTextField3.getText();
            sinopsis = jTextArea1.getText();
            PilihKursi kursi = new PilihKursi(judul, jumlah, harga, hargavip);
            kursi.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //mengambil isi array dan menampilkan ke text area
        jTextArea1.setText(sin.getSinopsisfilm());
        jTextField1.setText(jud.getJudulfilm());
        //jTextField4.setText(jum.getJumlahTiket());
        //memanggil array pada kelas Harga dan HargaVip
        jTextField2.setText(har.getHargafilm());
        jTextField3.setText(harV.getHargafilm());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:\
        //mengambil isi array dan menampilkan ke text area
        jTextArea1.setText(sin.getSinopsisfilm1());
        jTextField1.setText(jud.getJudulfilm1());
        //jTextField4.setText(jum.JumlahTiket1());
        jTextField2.setText(har.getHargafilm1());
        jTextField3.setText(harV.getHargafilm1());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //mengambil isi array dan menampilkan ke text area
        jTextArea1.setText(sin.getSinopsisfilm2());
        jTextField1.setText(jud.getJudulfilm2());
        //jTextField4.setText(jum.JumlahTiket2());
        jTextField2.setText(har.getHargafilm2());
        jTextField3.setText(harV.getHargafilm2());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //mengambil isi array dan menampilkan ke text area
        jTextArea1.setText(sin.getSinopsisfilm3());
        jTextField1.setText(jud.getJudulfilm3());
        //jTextField4.setText(jum.JumlahTiket3());
        jTextField2.setText(har.getHargafilm3());
        jTextField3.setText(harV.getHargafilm3());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinopsisFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinopsisFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinopsisFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinopsisFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SinopsisFilm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
